### ISSUE TITLE
Upload theme in chrome web store

### ISSUE THREAD

**Issue by Mikael-R** [getomni/google-chrome-omni#1]
https://smallbusiness.chron.com/upload-theme-google-chrome-store-43005.html

**Comment by mateus4k** [comment]
Up!

**Comment by mateushnsoares** [comment]
Up!

**Comment by joaopcm** [comment]
up!

**Comment by raphaeldevs** [comment]
up!

**Comment by jpedroschmitz** [comment]
Hey guys, 

We have submitted the theme to the Chrome Store and are waiting for approval.

As soon as we get the approval, we will be merging #4 and it will be easier to install the theme 💜

**Comment by jpedroschmitz** [comment]
The theme was published 🎉 

You can find it at [this link](https://chrome.google.com/webstore/detail/omni-dark-theme-for-chrom/loclkialbcifjohhglkomgamgpolpcoh).

Don't forget to install it and add a review. Feedbacks are appreciated 💜
